/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogyoneticisindex;

import blogyoneticisi.siniflar.genel.Araclar;
import blogyoneticisi.siniflar.model.Blog;
import blogyoneticisi.siniflar.model.BlogDetay;
import blogyoneticisi.siniflar.model.Kullanici;
import blogyoneticisi.siniflar.veritabani.VeritabaniIslemleri;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lenovo
 */
public class BlogYoneticisiView extends javax.swing.JFrame {
    public List<Blog> blogListesi;
    public BlogDetay seciliBlog = null;
    public List<Kullanici> kullaniciListesi;
    public Kullanici seciliKullanici = null;
    public BlogYoneticisiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogYeniBlogOlustur = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaBlogBasligiDialogBlogOlustur = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaBlogAciklamaDialogBlogOlustur = new javax.swing.JTextArea();
        jComboBoxKullaniciListesi = new javax.swing.JComboBox<>();
        jButtonBlogOlustur = new javax.swing.JButton();
        jDialogKullaniciBilgisiDetay = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldAdSoyadDialogKullaniciDetay = new javax.swing.JTextField();
        jTextFieldKullaniciAdiDialogKullaniciDetay = new javax.swing.JTextField();
        jPasswordFieldSifreDialogKullaniciDetay = new javax.swing.JPasswordField();
        jComboBoxKullaniciIzinlerDialogKullaniciDetay = new javax.swing.JComboBox<>();
        jButtonBlogSahibiniGüncelle = new javax.swing.JButton();
        jDialogKullaniciBilgileriniDüzenle = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelKullaniciIdDuzenle = new javax.swing.JLabel();
        jTextFieldAdSoyadDuzenle = new javax.swing.JTextField();
        jTextFieldKullaniciEmailDuzenle = new javax.swing.JTextField();
        jPasswordFieldSifreDuzenle = new javax.swing.JPasswordField();
        jComboBoxKullaniciIzinlerDüzenle = new javax.swing.JComboBox<>();
        jButtonKullaniciFormuTemizle = new javax.swing.JButton();
        jButtonKullaniciEkle = new javax.swing.JButton();
        jButtonKullaniciGüncelle = new javax.swing.JButton();
        KullaniciSil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBlogBasligi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaBlogAciklama = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelBlogSahibi = new javax.swing.JLabel();
        jLabelBlogOlusturmaTarihi = new javax.swing.JLabel();
        jLabelToplamGirdiSayisi = new javax.swing.JLabel();
        jLabelToplamYorumSayisi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBlogBilgisiGuncelle = new javax.swing.JButton();
        jButtonYeniBlogOlustur = new javax.swing.JButton();
        jButtonKullaniciBilgisiGörüntüle = new javax.swing.JButton();
        jButtonKullaniciİslemleri = new javax.swing.JButton();
        jButtonProgramiKapat = new javax.swing.JButton();
        jButtonBloguTamamenSil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxBlogListesi = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Yeni Blog Olustur"));

        jLabel9.setText("Blog Basligi");

        jLabel10.setText("Acıklama");

        jLabel11.setText("Blog Sahibi");

        jTextAreaBlogBasligiDialogBlogOlustur.setColumns(20);
        jTextAreaBlogBasligiDialogBlogOlustur.setRows(5);
        jScrollPane3.setViewportView(jTextAreaBlogBasligiDialogBlogOlustur);

        jTextAreaBlogAciklamaDialogBlogOlustur.setColumns(20);
        jTextAreaBlogAciklamaDialogBlogOlustur.setRows(5);
        jScrollPane4.setViewportView(jTextAreaBlogAciklamaDialogBlogOlustur);

        jComboBoxKullaniciListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKullaniciListesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jComboBoxKullaniciListesi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel10)))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxKullaniciListesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonBlogOlustur.setText("Blog Olustur");
        jButtonBlogOlustur.setToolTipText("");
        jButtonBlogOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBlogOlusturActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogYeniBlogOlusturLayout = new javax.swing.GroupLayout(jDialogYeniBlogOlustur.getContentPane());
        jDialogYeniBlogOlustur.getContentPane().setLayout(jDialogYeniBlogOlusturLayout);
        jDialogYeniBlogOlusturLayout.setHorizontalGroup(
            jDialogYeniBlogOlusturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogYeniBlogOlusturLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogYeniBlogOlusturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogYeniBlogOlusturLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBlogOlustur)))
                .addContainerGap())
        );
        jDialogYeniBlogOlusturLayout.setVerticalGroup(
            jDialogYeniBlogOlusturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogYeniBlogOlusturLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBlogOlustur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Kullanıcı Bilgileri"));

        jLabel12.setText("Kullanıcı Ad Soyad:");

        jLabel13.setText("Kullanıcı Adi(email):");

        jLabel14.setText("Sifre:");

        jLabel15.setText("Kullanıcı Izin:");

        jTextFieldAdSoyadDialogKullaniciDetay.setText("jTextField1");

        jTextFieldKullaniciAdiDialogKullaniciDetay.setText("jTextField2");

        jPasswordFieldSifreDialogKullaniciDetay.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldAdSoyadDialogKullaniciDetay)
                    .addComponent(jTextFieldKullaniciAdiDialogKullaniciDetay)
                    .addComponent(jPasswordFieldSifreDialogKullaniciDetay, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jComboBoxKullaniciIzinlerDialogKullaniciDetay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldAdSoyadDialogKullaniciDetay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldKullaniciAdiDialogKullaniciDetay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jPasswordFieldSifreDialogKullaniciDetay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxKullaniciIzinlerDialogKullaniciDetay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtonBlogSahibiniGüncelle.setText("Güncelle");
        jButtonBlogSahibiniGüncelle.setToolTipText("");
        jButtonBlogSahibiniGüncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBlogSahibiniGüncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogKullaniciBilgisiDetayLayout = new javax.swing.GroupLayout(jDialogKullaniciBilgisiDetay.getContentPane());
        jDialogKullaniciBilgisiDetay.getContentPane().setLayout(jDialogKullaniciBilgisiDetayLayout);
        jDialogKullaniciBilgisiDetayLayout.setHorizontalGroup(
            jDialogKullaniciBilgisiDetayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKullaniciBilgisiDetayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogKullaniciBilgisiDetayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBlogSahibiniGüncelle)
                .addContainerGap())
        );
        jDialogKullaniciBilgisiDetayLayout.setVerticalGroup(
            jDialogKullaniciBilgisiDetayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKullaniciBilgisiDetayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBlogSahibiniGüncelle)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Kullanici Bilgileri"));

        jLabel16.setText("Secili Kullanici ID");

        jLabel17.setText("Ad Soyad");

        jLabel18.setText("Kullanici Adi(e-mail)");

        jLabel19.setText("Sifre");

        jLabel20.setText("Kullanici İzin");

        jLabelKullaniciIdDuzenle.setText("jLabel21");

        jComboBoxKullaniciIzinlerDüzenle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yazar (Girdi ekleyebilir)", "Okur (Yorum ekleyebilir)", "Admin (Tüm verilere ulaşabilir)" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAdSoyadDuzenle)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabelKullaniciIdDuzenle)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldSifreDuzenle)
                                    .addComponent(jComboBoxKullaniciIzinlerDüzenle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel18)
                        .addGap(36, 36, 36)
                        .addComponent(jTextFieldKullaniciEmailDuzenle)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabelKullaniciIdDuzenle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldAdSoyadDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldKullaniciEmailDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jPasswordFieldSifreDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBoxKullaniciIzinlerDüzenle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButtonKullaniciFormuTemizle.setText("Yeni");
        jButtonKullaniciFormuTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKullaniciFormuTemizleActionPerformed(evt);
            }
        });

        jButtonKullaniciEkle.setText("Ekle");
        jButtonKullaniciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKullaniciEkleActionPerformed(evt);
            }
        });

        jButtonKullaniciGüncelle.setText("Güncelle");
        jButtonKullaniciGüncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKullaniciGüncelleActionPerformed(evt);
            }
        });

        KullaniciSil.setText("Sil");
        KullaniciSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KullaniciSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogKullaniciBilgileriniDüzenleLayout = new javax.swing.GroupLayout(jDialogKullaniciBilgileriniDüzenle.getContentPane());
        jDialogKullaniciBilgileriniDüzenle.getContentPane().setLayout(jDialogKullaniciBilgileriniDüzenleLayout);
        jDialogKullaniciBilgileriniDüzenleLayout.setHorizontalGroup(
            jDialogKullaniciBilgileriniDüzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKullaniciBilgileriniDüzenleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogKullaniciBilgileriniDüzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogKullaniciBilgileriniDüzenleLayout.createSequentialGroup()
                        .addComponent(jButtonKullaniciFormuTemizle)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonKullaniciEkle)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonKullaniciGüncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KullaniciSil)))
                .addContainerGap())
        );
        jDialogKullaniciBilgileriniDüzenleLayout.setVerticalGroup(
            jDialogKullaniciBilgileriniDüzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKullaniciBilgileriniDüzenleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogKullaniciBilgileriniDüzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKullaniciFormuTemizle)
                    .addComponent(jButtonKullaniciEkle)
                    .addComponent(jButtonKullaniciGüncelle)
                    .addComponent(KullaniciSil))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BlogYönetim Konsolu");
        jLabel1.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Blog Bilgisi"));

        jLabel3.setText("Blog Baslığı");

        jLabel4.setText("Acıklama");

        jTextAreaBlogBasligi.setColumns(20);
        jTextAreaBlogBasligi.setRows(5);
        jScrollPane1.setViewportView(jTextAreaBlogBasligi);

        jTextAreaBlogAciklama.setColumns(20);
        jTextAreaBlogAciklama.setRows(5);
        jScrollPane2.setViewportView(jTextAreaBlogAciklama);

        jLabel5.setText("Blogun Sahibi Olan Kullanici");

        jLabel6.setText("Blogun Olusturma Tarihi");

        jLabel7.setText("Blogdaki Toplam Girdi Sayısı");

        jLabel8.setText("Blogdaki Toplam Yorum Sayisi");

        jLabelBlogSahibi.setText("jLabel9");

        jLabelBlogOlusturmaTarihi.setText("jLabel10");

        jLabelToplamGirdiSayisi.setText("jLabel11");

        jLabelToplamYorumSayisi.setText("jLabel12");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("İslemler"));

        jButtonBlogBilgisiGuncelle.setText("BLOG BİLGİSİ GÜNCELLE");
        jButtonBlogBilgisiGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBlogBilgisiGuncelleActionPerformed(evt);
            }
        });

        jButtonYeniBlogOlustur.setText("YENİ BLOG OLUŞTUR");
        jButtonYeniBlogOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYeniBlogOlusturActionPerformed(evt);
            }
        });

        jButtonKullaniciBilgisiGörüntüle.setText("KULLANICI BİLGİSİ GÖRÜNTÜLE");
        jButtonKullaniciBilgisiGörüntüle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKullaniciBilgisiGörüntüleActionPerformed(evt);
            }
        });

        jButtonKullaniciİslemleri.setText("KULLANICI İŞLEMLERİ");
        jButtonKullaniciİslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKullaniciİslemleriActionPerformed(evt);
            }
        });

        jButtonProgramiKapat.setText("PROGRAMI KAPAT");
        jButtonProgramiKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProgramiKapatActionPerformed(evt);
            }
        });

        jButtonBloguTamamenSil.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jButtonBloguTamamenSil.setForeground(new java.awt.Color(255, 51, 51));
        jButtonBloguTamamenSil.setText("BLOGU TAMAMEN SİL");
        jButtonBloguTamamenSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBloguTamamenSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonBloguTamamenSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBlogBilgisiGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKullaniciBilgisiGörüntüle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonKullaniciİslemleri, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonYeniBlogOlustur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProgramiKapat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBlogBilgisiGuncelle)
                    .addComponent(jButtonYeniBlogOlustur))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKullaniciBilgisiGörüntüle)
                    .addComponent(jButtonKullaniciİslemleri))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProgramiKapat)
                    .addComponent(jButtonBloguTamamenSil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBlogOlusturmaTarihi)
                            .addComponent(jLabelBlogSahibi)
                            .addComponent(jLabelToplamGirdiSayisi)
                            .addComponent(jLabelToplamYorumSayisi))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelBlogSahibi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelBlogOlusturmaTarihi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelToplamGirdiSayisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelToplamYorumSayisi))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Blog Seciniz:");

        jComboBoxBlogListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBlogListesiActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxBlogListesi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxBlogListesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKullaniciFormuTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKullaniciFormuTemizleActionPerformed
     jLabelKullaniciIdDuzenle.setText("");
     jTextFieldAdSoyadDuzenle.setText("");
     jTextFieldKullaniciEmailDuzenle.setText("");
     jPasswordFieldSifreDuzenle.setText("");
     jComboBoxKullaniciIzinlerDüzenle.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonKullaniciFormuTemizleActionPerformed

    private void jButtonKullaniciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKullaniciEkleActionPerformed
        Kullanici k=new Kullanici();
       k.setK_adSoyad(jTextFieldAdSoyadDuzenle.getText());
       k.setK_Email(jTextFieldKullaniciEmailDuzenle.getText());
       k.setK_Izin(jComboBoxKullaniciIzinlerDüzenle.getSelectedItem().toString().substring(0,1));
       k.setK_Sifre(jPasswordFieldSifreDuzenle.getText());
       k.setKayitTarih(Araclar.yeniTimeStampOlustur());
       VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            vt.kullaniciOlustur(k);
            vt.baglantiyiKes();
            kullaniciTablosuDoldur();
        } catch (Exception e) {
            Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
    }//GEN-LAST:event_jButtonKullaniciEkleActionPerformed

    private void jButtonKullaniciGüncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKullaniciGüncelleActionPerformed
              if(jLabelKullaniciIdDuzenle.getText().trim().length()==0){
           return;
       }
        
        Kullanici k=new Kullanici();
        k.setK_ID(Integer.valueOf(jLabelKullaniciIdDuzenle.getText()));
       k.setK_adSoyad(jTextFieldAdSoyadDuzenle.getText());
       k.setK_Email(jTextFieldKullaniciEmailDuzenle.getText());
       k.setK_Izin(jComboBoxKullaniciIzinlerDüzenle.getSelectedItem().toString().substring(0,1));
       k.setK_Sifre(jPasswordFieldSifreDuzenle.getText());
       VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            boolean sonuc=vt.kullaniciBilgisiGuncelle(k);
            vt.baglantiyiKes();
            if(sonuc){
            kullaniciTablosuDoldur();
            }
        } catch (Exception e) {
            Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
    }//GEN-LAST:event_jButtonKullaniciGüncelleActionPerformed

    private void KullaniciSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KullaniciSilActionPerformed
                 if(jLabelKullaniciIdDuzenle.getText().trim().length()==0){
             Araclar.mesajGoster("Önce bir blog seciniz..","UYARI");
             return;
       }
         int cevap=Araclar.soruSor("Kullanıcıyı silmek istediğinizden "
         +"eminmisiniz?(Kullanıcının tüm blog , girdi ve"
         +" yorumları otoatik olarak silinecek)");        
          if(cevap!=0)
              return;
          
          VeritabaniIslemleri vt=new VeritabaniIslemleri();
          try {
            vt.baglan();
            Kullanici k=new Kullanici();
            k.setK_ID(Integer.valueOf(jLabelKullaniciIdDuzenle.getText()));
            vt.kullaniciyiSil(k);
            vt.baglantiyiKes();
            kullaniciTablosuDoldur();
            formuTemizle();
            baslangicBilgisiniCek();
        } catch (Exception e) {
            Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
    }//GEN-LAST:event_KullaniciSilActionPerformed

    private void jButtonBlogSahibiniGüncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlogSahibiniGüncelleActionPerformed
             this.seciliBlog.getKullanici().setK_adSoyad(jTextFieldAdSoyadDialogKullaniciDetay.getText());
       this.seciliBlog.getKullanici().setK_Email(jTextFieldKullaniciAdiDialogKullaniciDetay.getText());
       this.seciliBlog.getKullanici().setK_Sifre(jPasswordFieldSifreDialogKullaniciDetay.getText());
       this.seciliBlog.getKullanici().setK_Izin(jComboBoxKullaniciIzinlerDialogKullaniciDetay.getSelectedItem().toString().substring(0,1));
       VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            vt.kullaniciBilgisiGuncelle(seciliBlog.getKullanici());
            vt.baglantiyiKes();
            jLabel12.setText(this.seciliBlog.getKullanici().getK_adSoyad());
        } catch (Exception e) {
            Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
    }//GEN-LAST:event_jButtonBlogSahibiniGüncelleActionPerformed

    private void jButtonBlogOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlogOlusturActionPerformed
       if(jTextAreaBlogBasligiDialogBlogOlustur.getText().trim().length()==0){
       Araclar.mesajGoster("Blog Basligi bos olamaz","HATA");
           return;
       }
       if(jTextAreaBlogAciklamaDialogBlogOlustur.getText().trim().length()==0){
       Araclar.mesajGoster("Bir aciklama giriniz","UYARI");
           return;
       }
       if(jComboBoxKullaniciListesi.getSelectedItem().toString().equals("Seciniz...")){
       Araclar.mesajGoster("Önce bir blog seciniz..","UYARI");
           return;
       }
       Blog b=new Blog();
       b.setAciklama(jTextAreaBlogAciklamaDialogBlogOlustur.getText());
       b.setBlogBaslik(jTextAreaBlogBasligiDialogBlogOlustur.getText());
       b.setK_ID(this.seciliKullanici.getK_ID());
       b.setOlusturmaTarihi(Araclar.yeniTimeStampOlustur());
        VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            vt.blogOlustur(b);
            vt.baglantiyiKes();
        } catch (Exception e) {
                 Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
       formuTemizle();
       baslangicBilgisiniCek();
    }//GEN-LAST:event_jButtonBlogOlusturActionPerformed

    private void jButtonBlogBilgisiGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlogBilgisiGuncelleActionPerformed
         if(seciliBlog==null){
         Araclar.mesajGoster("Önce bir blog seciniz!!!", "UYARI");
         return;
     }
     seciliBlog.setAciklama(jTextAreaBlogAciklama.getText());
     seciliBlog.setBlogBaslik(jTextAreaBlogBasligi.getText());
     VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            vt.blogBilgisiGuncelle((Blog) seciliBlog);
            vt.baglantiyiKes();
        } catch (Exception e) {
            Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
    }//GEN-LAST:event_jButtonBlogBilgisiGuncelleActionPerformed

    private void jButtonYeniBlogOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYeniBlogOlusturActionPerformed
            diyalogTemizleBlogOlustur();
     VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            this.kullaniciListesi=vt.tumKullanicilariGetir();
            vt.baglantiyiKes();
        } catch (Exception e) {
               Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
        jComboBoxKullaniciListesi.addItem("Seciniz...");
        if(this.kullaniciListesi!=null){
            for(Kullanici k:this.kullaniciListesi){
            if(k.getK_Izin().equals("A")  ||  k.getK_Izin().equals("Y")){
                jComboBoxKullaniciListesi.addItem(k.getK_adSoyad() + " ( " + k.getK_Email()+ " )");
            }
            
            }
        
        }
        jDialogYeniBlogOlustur.pack();
        jDialogYeniBlogOlustur.setLocationRelativeTo(this);
        jDialogYeniBlogOlustur.setVisible(true);
    }//GEN-LAST:event_jButtonYeniBlogOlusturActionPerformed

    private void jButtonKullaniciBilgisiGörüntüleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKullaniciBilgisiGörüntüleActionPerformed
     if (this.seciliBlog == null) {
            Araclar.mesajGoster("Önce bir blog seçiniz!!!", "UYARI");
            return;
        }
        VeritabaniIslemleri vi = new VeritabaniIslemleri();
        try {
            vi.baglan();
            this.seciliKullanici = vi.kullaniciBilgisiGetir(this.seciliBlog.getK_ID());
            vi.baglantiyiKes();
        } catch (Exception ex) {
            Araclar.mesajGoster("Bir hata oluştu:Açıklama"
                    + ex.getMessage(), "HATA");
        }

        jDialogKullaniciBilgisiDetay.pack();
        jDialogKullaniciBilgisiDetay.setLocationRelativeTo(this);
        jDialogKullaniciBilgisiDetay.setVisible(true);

        jComboBoxKullaniciIzinlerDialogKullaniciDetay.setModel(new DefaultComboBoxModel());
        jComboBoxKullaniciIzinlerDialogKullaniciDetay.addItem("Yazar (Girdi ekleyebilir)");
        jComboBoxKullaniciIzinlerDialogKullaniciDetay.addItem("Okur (Yorum ekleyebilir)");
        jComboBoxKullaniciIzinlerDialogKullaniciDetay.addItem("Admin (Tüm verilere ulaşabilir)");

        jTextFieldAdSoyadDialogKullaniciDetay.setText(this.seciliKullanici.getK_adSoyad());
        jTextFieldKullaniciAdiDialogKullaniciDetay.setText(this.seciliKullanici.getK_Email());
        jPasswordFieldSifreDialogKullaniciDetay.setText(this.seciliKullanici.getK_Sifre());

        switch (this.seciliKullanici.getK_Izin().charAt(0)) {
            case 'Y':
                jComboBoxKullaniciIzinlerDialogKullaniciDetay.setSelectedIndex(0);
                break;
            case 'O':
                jComboBoxKullaniciIzinlerDialogKullaniciDetay.setSelectedIndex(1);
                break;
            case 'A':
                jComboBoxKullaniciIzinlerDialogKullaniciDetay.setSelectedIndex(2);
                break;
            default:
                break;
         }
    }//GEN-LAST:event_jButtonKullaniciBilgisiGörüntüleActionPerformed

    private void jButtonKullaniciİslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKullaniciİslemleriActionPerformed
                //Kullanıcı bilgilerinin düzenlenmesini
        //sağlayan diyalog penceresini aç
        jDialogKullaniciBilgileriniDüzenle.pack();
        jDialogKullaniciBilgileriniDüzenle.setLocationRelativeTo(this);
        jDialogKullaniciBilgileriniDüzenle.setVisible(true);
        //Tabloyu doldur
        kullaniciTablosuDoldur();
        ListSelectionModel lsm = jTable1.getSelectionModel();
        lsm.addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent e) {
                int row = jTable1.getSelectedRow();
                if (row == -1) {
                    return;
                }
                jLabelKullaniciIdDuzenle.setText(jTable1.getValueAt(row, 0).toString());
                jTextFieldKullaniciEmailDuzenle.setText(jTable1.getValueAt(row, 1).toString());
                jPasswordFieldSifreDuzenle.setText(jTable1.getValueAt(row, 2).toString());
                jTextFieldAdSoyadDuzenle.setText(jTable1.getValueAt(row, 3).toString());
                switch (jTable1.getValueAt(row, 4).toString().charAt(0)) {
                    case 'Y':
                        jComboBoxKullaniciIzinlerDüzenle.setSelectedIndex(0);
                        break;
                    case 'O':
                        jComboBoxKullaniciIzinlerDüzenle.setSelectedIndex(1);
                        break;
                    case 'A':
                        jComboBoxKullaniciIzinlerDüzenle.setSelectedIndex(2);
                        break;
                    default:
                        break;
                }
            }
        });
    }//GEN-LAST:event_jButtonKullaniciİslemleriActionPerformed

    private void jButtonBloguTamamenSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBloguTamamenSilActionPerformed
         if (this.seciliBlog == null) {
            return;
        }
        int cevap = Araclar.soruSor("Bloğu silmek istediğinizden "
                + "emin misiniz(Blogtaki girdi ve "
                + "yorumlar otomatik olarak silinecek)?");
        if (cevap != 0) {
            return;
        }
        VeritabaniIslemleri vi = new VeritabaniIslemleri();
        try {
            vi.baglan();
            vi.bloguSil((Blog) seciliBlog);
            vi.baglantiyiKes();
            formuTemizle();
            baslangicBilgisiniCek();
        } catch (Exception ex) {
            Araclar.mesajGoster("Bir hata oluştu:Açıklama"
                    + ex.getMessage(), "HATA");
        }
    }//GEN-LAST:event_jButtonBloguTamamenSilActionPerformed

    private void jButtonProgramiKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProgramiKapatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonProgramiKapatActionPerformed

    private void jComboBoxBlogListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBlogListesiActionPerformed
     if (jComboBoxBlogListesi.getSelectedItem().toString().equals("Seciniz...")) {
            formuTemizle();
            return;
        }
        String gecici=jComboBoxBlogListesi.getSelectedItem().toString();
        for (Blog b : this.blogListesi) {
            if(gecici.contains(b.getBlogBaslik()) && gecici.contains(Araclar.tarihZamnGoster(b.getOlusturmaTarihi()))){
                VeritabaniIslemleri vt=new VeritabaniIslemleri();
                try {
                    vt.baglan();
                    this.seciliBlog=vt.blogDetayGetir(b.getB_ID());
                    vt.baglantiyiKes();
                    break;
                    
                } catch (Exception e) {
                    Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
                }
            
            }
            
        }
        
          jTextAreaBlogBasligi.setText(seciliBlog.getBlogBaslik());
        jTextAreaBlogAciklama.setText(seciliBlog.getAciklama());
        System.out.println(jTextAreaBlogAciklama.getText());
        jLabelBlogOlusturmaTarihi.setText(
                Araclar.tarihZamnGoster(
                seciliBlog.getOlusturmaTarihi()));
        jLabelBlogSahibi.setText(seciliBlog.getKullanici().getK_adSoyad());
        jLabelToplamGirdiSayisi.setText(String.valueOf(seciliBlog.getGirdiSayisi()));
        jLabelToplamYorumSayisi.setText(String.valueOf(seciliBlog.getYorumSayisi()));
    }//GEN-LAST:event_jComboBoxBlogListesiActionPerformed

    private void jComboBoxKullaniciListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKullaniciListesiActionPerformed
         if (this.kullaniciListesi == null) {
            Araclar.mesajGoster("Kullanıcı Listesi Boş!!!", "UYARI");
            return;
        }
        String gecici = jComboBoxKullaniciListesi.getSelectedItem().toString();
        if (gecici.equals("Seçiniz...")) {
            Araclar.mesajGoster("Önce bir kullanıcı seçiniz!!!", "UYARI");
            return;
        }

        for(Kullanici k : this.kullaniciListesi) {
            if (gecici.contains(k.getK_Email())) {
                this.seciliKullanici = k;
            }
        }
    }//GEN-LAST:event_jComboBoxKullaniciListesiActionPerformed
public void formuTemizle(){
    jLabelBlogOlusturmaTarihi.setText("");
    jLabelBlogSahibi.setText("");
    jLabelToplamGirdiSayisi.setText("-");
    jLabelToplamYorumSayisi.setText("-");
    jTextAreaBlogAciklama.setText("");
    jTextAreaBlogBasligi.setText("");
 }
    public void diyalogTemizleBlogOlustur(){
        //Blog Olustur Diyaloğu
        jTextAreaBlogAciklamaDialogBlogOlustur.setText("");
        jTextAreaBlogBasligiDialogBlogOlustur.setText("");
        jComboBoxKullaniciListesi.setModel(new DefaultComboBoxModel());

    }
    public void baslangicBilgisiniCek(){
        try {
            VeritabaniIslemleri vt=new VeritabaniIslemleri();
            vt.baglan();
            this.blogListesi=vt.tumBloglariGetir();
            jComboBoxBlogListesi.setModel(new DefaultComboBoxModel());
            jComboBoxBlogListesi.addItem("Seciniz...");
            if(this.blogListesi==null){
                return;}
            for (Blog b : this.blogListesi) {
                jComboBoxBlogListesi.addItem(Araclar.tarihZamnGoster(b.getOlusturmaTarihi())
                +"...."
                +b.getBlogBaslik());
                
            }
            vt.baglantiyiKes();
        } catch (Exception e) {
        Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
    }
    public void kullaniciTablosuDoldur(){
        VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            Object[][] veri=kullaniciBilgisiniIkiBoyutluDiziyeCevir(vt.tumKullanicilariGetir());
            Object [] baslik=vt.tabloKolonAdlariniGetir("kullanicilar");
            jTable1.setModel(Araclar.tabloIcinModelOlustur(baslik, veri));
            TableModel model=new DefaultTableModel(veri,baslik);
            jTable1.setModel(model);
            vt.baglantiyiKes();
        } catch (Exception e) {
            Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
    
    }
       public Object[][] kullaniciBilgisiniIkiBoyutluDiziyeCevir(List<Kullanici> kList) {
        if (kList == null) {
            return null;
        }
        Object[][] sonuc = new Object[kList.size()][6];

        for (int i = 0; i < kList.size(); i++) {
            sonuc[i][0] = kList.get(i).getK_ID();
            sonuc[i][1] = kList.get(i).getK_Email();
            sonuc[i][2] = kList.get(i).getK_Sifre();
            sonuc[i][3] = kList.get(i).getK_adSoyad();
            sonuc[i][4] = kList.get(i).getK_Izin();
            sonuc[i][5] = kList.get(i).getKayitTarih();
        }


        return sonuc;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlogYoneticisiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlogYoneticisiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlogYoneticisiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlogYoneticisiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
                new BlogYoneticisiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KullaniciSil;
    private javax.swing.JButton jButtonBlogBilgisiGuncelle;
    private javax.swing.JButton jButtonBlogOlustur;
    private javax.swing.JButton jButtonBlogSahibiniGüncelle;
    private javax.swing.JButton jButtonBloguTamamenSil;
    private javax.swing.JButton jButtonKullaniciBilgisiGörüntüle;
    private javax.swing.JButton jButtonKullaniciEkle;
    private javax.swing.JButton jButtonKullaniciFormuTemizle;
    private javax.swing.JButton jButtonKullaniciGüncelle;
    private javax.swing.JButton jButtonKullaniciİslemleri;
    private javax.swing.JButton jButtonProgramiKapat;
    private javax.swing.JButton jButtonYeniBlogOlustur;
    private javax.swing.JComboBox<String> jComboBoxBlogListesi;
    private javax.swing.JComboBox<String> jComboBoxKullaniciIzinlerDialogKullaniciDetay;
    private javax.swing.JComboBox<String> jComboBoxKullaniciIzinlerDüzenle;
    private javax.swing.JComboBox<String> jComboBoxKullaniciListesi;
    private javax.swing.JDialog jDialogKullaniciBilgileriniDüzenle;
    private javax.swing.JDialog jDialogKullaniciBilgisiDetay;
    private javax.swing.JDialog jDialogYeniBlogOlustur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBlogOlusturmaTarihi;
    private javax.swing.JLabel jLabelBlogSahibi;
    private javax.swing.JLabel jLabelKullaniciIdDuzenle;
    private javax.swing.JLabel jLabelToplamGirdiSayisi;
    private javax.swing.JLabel jLabelToplamYorumSayisi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordFieldSifreDialogKullaniciDetay;
    private javax.swing.JPasswordField jPasswordFieldSifreDuzenle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaBlogAciklama;
    private javax.swing.JTextArea jTextAreaBlogAciklamaDialogBlogOlustur;
    private javax.swing.JTextArea jTextAreaBlogBasligi;
    private javax.swing.JTextArea jTextAreaBlogBasligiDialogBlogOlustur;
    private javax.swing.JTextField jTextFieldAdSoyadDialogKullaniciDetay;
    private javax.swing.JTextField jTextFieldAdSoyadDuzenle;
    private javax.swing.JTextField jTextFieldKullaniciAdiDialogKullaniciDetay;
    private javax.swing.JTextField jTextFieldKullaniciEmailDuzenle;
    // End of variables declaration//GEN-END:variables
}
