/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blogyoneticisiindex;

import blogyoneticisi.siniflar.genel.Araclar;
import blogyoneticisi.siniflar.model.Blog;
import blogyoneticisi.siniflar.model.BlogDetay;
import blogyoneticisi.siniflar.model.Kullanici;
import blogyoneticisi.siniflar.veritabani.VeritabaniIslemleri;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lenovo
 */
public class BlogYoneticisiView extends javax.swing.JFrame {
    public List<Blog> blogListesi;
    public BlogDetay seciliBlog = null;
    public List<Kullanici> kullaniciListesi;
    public Kullanici seciliKullanici = null;
    public BlogYoneticisiView() {
        initComponents();
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogYeniBlogOlustur = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        blogBasligi = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        aciklama = new javax.swing.JTextArea();
        blogSahibiSeciniz = new javax.swing.JComboBox<>();
        blogOlustur = new javax.swing.JButton();
        jDialogKullaniciBilgisiDetay = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kullaniciAdSoyad = new javax.swing.JTextField();
        kullaniciAdi = new javax.swing.JTextField();
        kullaniciSifre = new javax.swing.JPasswordField();
        kullaniciIzin = new javax.swing.JComboBox<>();
        kullaniciGuncelle = new javax.swing.JButton();
        jDialogKullaniciBilgileriDuzenle = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        IdGoster = new javax.swing.JLabel();
        kAdSoyad = new javax.swing.JTextField();
        kAdi = new javax.swing.JTextField();
        kSifre = new javax.swing.JPasswordField();
        kIzin = new javax.swing.JComboBox<>();
        yeniKullaniciEkle = new javax.swing.JButton();
        ekle = new javax.swing.JButton();
        KGüncelle = new javax.swing.JButton();
        kSil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxBlogListesi = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBlogBasligi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaBlogAciklama = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelBlogSahibi = new javax.swing.JLabel();
        jLabelOlusturulmaTarihi = new javax.swing.JLabel();
        jLabelToplamGirdiSayisi = new javax.swing.JLabel();
        jLabelToplamYorumSayisi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBlogBilgisiGuncelle = new javax.swing.JButton();
        jButtonYeniBlogOlustur = new javax.swing.JButton();
        jButtonKullaniciBilgisiGoruntule = new javax.swing.JButton();
        jButtonKullaniciİslemleri = new javax.swing.JButton();
        jButtonBloguTamamenSil = new javax.swing.JButton();
        jButtonProgramiKapat = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Yeni Blog Olustur"));

        jLabel9.setText("Blog Baslığı");

        jLabel10.setText("Açıklama");

        jLabel11.setText("Blog Sahibi");

        blogBasligi.setColumns(20);
        blogBasligi.setRows(5);
        jScrollPane3.setViewportView(blogBasligi);

        aciklama.setColumns(20);
        aciklama.setRows(5);
        jScrollPane4.setViewportView(aciklama);

        blogSahibiSeciniz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seciniz..." }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addComponent(jScrollPane4))
                    .addComponent(blogSahibiSeciniz, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(blogSahibiSeciniz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        blogOlustur.setText("BLOG OLUŞTUR");
        blogOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogOlusturActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogYeniBlogOlusturLayout = new javax.swing.GroupLayout(jDialogYeniBlogOlustur.getContentPane());
        jDialogYeniBlogOlustur.getContentPane().setLayout(jDialogYeniBlogOlusturLayout);
        jDialogYeniBlogOlusturLayout.setHorizontalGroup(
            jDialogYeniBlogOlusturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogYeniBlogOlusturLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogYeniBlogOlusturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogYeniBlogOlusturLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(blogOlustur)))
                .addContainerGap())
        );
        jDialogYeniBlogOlusturLayout.setVerticalGroup(
            jDialogYeniBlogOlusturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogYeniBlogOlusturLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(blogOlustur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Kullanıcı Bilgileri"));

        jLabel12.setText("Kullanıcı Ad Soyad");

        jLabel13.setText("Kullanıcı Adı(Email)");

        jLabel14.setText("Şifre");

        jLabel15.setText("Kullanıcı Izin");

        kullaniciIzin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin(Tüm Verilere Ulaşabilir)" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullaniciSifre)
                    .addComponent(kullaniciIzin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kullaniciAdi)
                    .addComponent(kullaniciAdSoyad))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(kullaniciAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(kullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(kullaniciIzin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        kullaniciGuncelle.setText("GÜNCELLE");
        kullaniciGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciGuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogKullaniciBilgisiDetayLayout = new javax.swing.GroupLayout(jDialogKullaniciBilgisiDetay.getContentPane());
        jDialogKullaniciBilgisiDetay.getContentPane().setLayout(jDialogKullaniciBilgisiDetayLayout);
        jDialogKullaniciBilgisiDetayLayout.setHorizontalGroup(
            jDialogKullaniciBilgisiDetayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKullaniciBilgisiDetayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogKullaniciBilgisiDetayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kullaniciGuncelle)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogKullaniciBilgisiDetayLayout.setVerticalGroup(
            jDialogKullaniciBilgisiDetayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKullaniciBilgisiDetayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kullaniciGuncelle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Kullanici Bilgileri"));

        jLabel16.setText("Seçili Kullanıcı ID");

        jLabel17.setText("Ad Soyad");

        jLabel18.setText("Kullanıcı Adı(Email)");

        jLabel19.setText("Şifre");

        jLabel20.setText("Kullanıcı İzin");
        jLabel20.setToolTipText("");

        IdGoster.setText("jLabel21");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IdGoster)
                    .addComponent(kSifre)
                    .addComponent(kIzin, 0, 638, Short.MAX_VALUE)
                    .addComponent(kAdi)
                    .addComponent(kAdSoyad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(IdGoster))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(kAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(kAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(kSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(kIzin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        yeniKullaniciEkle.setText("Yeni");
        yeniKullaniciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeniKullaniciEkleActionPerformed(evt);
            }
        });

        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        KGüncelle.setText("Güncelle");
        KGüncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KGüncelleActionPerformed(evt);
            }
        });

        kSil.setText("Sil");
        kSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogKullaniciBilgileriDuzenleLayout = new javax.swing.GroupLayout(jDialogKullaniciBilgileriDuzenle.getContentPane());
        jDialogKullaniciBilgileriDuzenle.getContentPane().setLayout(jDialogKullaniciBilgileriDuzenleLayout);
        jDialogKullaniciBilgileriDuzenleLayout.setHorizontalGroup(
            jDialogKullaniciBilgileriDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKullaniciBilgileriDuzenleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogKullaniciBilgileriDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogKullaniciBilgileriDuzenleLayout.createSequentialGroup()
                        .addComponent(yeniKullaniciEkle)
                        .addGap(18, 18, 18)
                        .addComponent(ekle)
                        .addGap(28, 28, 28)
                        .addComponent(KGüncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kSil)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogKullaniciBilgileriDuzenleLayout.setVerticalGroup(
            jDialogKullaniciBilgileriDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogKullaniciBilgileriDuzenleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogKullaniciBilgileriDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeniKullaniciEkle)
                    .addComponent(ekle)
                    .addComponent(KGüncelle)
                    .addComponent(kSil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLOG YONETİM KONSOLU");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Bir Blog Seciniz:");

        jComboBoxBlogListesi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxBlogListesiİtemStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Blog Bilgisi"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Blog Baslığı");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Açıklama");
        jLabel4.setToolTipText("");

        jTextAreaBlogBasligi.setColumns(20);
        jTextAreaBlogBasligi.setRows(5);
        jScrollPane1.setViewportView(jTextAreaBlogBasligi);

        jTextAreaBlogAciklama.setColumns(20);
        jTextAreaBlogAciklama.setRows(5);
        jScrollPane2.setViewportView(jTextAreaBlogAciklama);

        jLabel5.setText("Bloğun Sahibi Olan Kullanıcı");

        jLabel6.setText("Bloğun Olusturulma Tarihi");

        jLabel7.setText("Blogdaki Toplam Girdi Sayisi");

        jLabel8.setText("Blogdaki Toplam Yorum Sayısı");

        jLabelBlogSahibi.setText("jLabel9");

        jLabelOlusturulmaTarihi.setText("jLabel10");

        jLabelToplamGirdiSayisi.setText("jLabel11");

        jLabelToplamYorumSayisi.setText("jLabel12");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("İslemler"));

        jButtonBlogBilgisiGuncelle.setText("BLOG BİLGİSİ GÜNCELLE");
        jButtonBlogBilgisiGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBlogBilgisiGuncelleActionPerformed(evt);
            }
        });

        jButtonYeniBlogOlustur.setText("YENİ BLOG OLUŞTUR");
        jButtonYeniBlogOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYeniBlogOlusturActionPerformed(evt);
            }
        });

        jButtonKullaniciBilgisiGoruntule.setText("KULLANICI BİLGİSİ GÖRÜNTÜLE");
        jButtonKullaniciBilgisiGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKullaniciBilgisiGoruntuleActionPerformed(evt);
            }
        });

        jButtonKullaniciİslemleri.setText("KULLANICI İŞLEMLERİ");
        jButtonKullaniciİslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKullaniciİslemleriActionPerformed(evt);
            }
        });

        jButtonBloguTamamenSil.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButtonBloguTamamenSil.setForeground(new java.awt.Color(255, 51, 0));
        jButtonBloguTamamenSil.setText("BLOĞU TAMAMEN SİL");
        jButtonBloguTamamenSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBloguTamamenSilActionPerformed(evt);
            }
        });

        jButtonProgramiKapat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonProgramiKapat.setText("PROGRAMI KAPAT");
        jButtonProgramiKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProgramiKapatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonKullaniciBilgisiGoruntule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBloguTamamenSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonBlogBilgisiGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonKullaniciİslemleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonYeniBlogOlustur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProgramiKapat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBlogBilgisiGuncelle)
                    .addComponent(jButtonYeniBlogOlustur))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKullaniciBilgisiGoruntule)
                    .addComponent(jButtonKullaniciİslemleri))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBloguTamamenSil)
                    .addComponent(jButtonProgramiKapat))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOlusturulmaTarihi)
                            .addComponent(jLabelBlogSahibi)
                            .addComponent(jLabelToplamGirdiSayisi)
                            .addComponent(jLabelToplamYorumSayisi))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelBlogSahibi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelOlusturulmaTarihi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelToplamGirdiSayisi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelToplamYorumSayisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar2.setBackground(new java.awt.Color(153, 153, 153));

        jMenu3.setText("Dosya");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Yardım");

        jMenu5.setText("Hakkımızda");
        jMenu4.add(jMenu5);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBlogListesi, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxBlogListesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBlogListesiİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxBlogListesiİtemStateChanged
        if (jComboBoxBlogListesi.getSelectedItem().toString().equals("Seciniz...")) {
            formuTemizle();
            return;
        }
        String gecici=jComboBoxBlogListesi.getSelectedItem().toString();
        for (Blog b : this.blogListesi) {
            if(gecici.contains(b.getBlogBaslik()) && gecici.contains(Araclar.tarihZamnGoster(b.getOlusturmaTarihi()))){
                VeritabaniIslemleri vt=new VeritabaniIslemleri();
                try {
                    vt.baglan();
                    this.seciliBlog=vt.blogDetayGetir(b.getB_ID());
                    vt.baglantiyiKes();
                    break;
                    
                } catch (Exception e) {
                    Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
                }
            
            }
            
        }
        
    }//GEN-LAST:event_jComboBoxBlogListesiİtemStateChanged

    private void jButtonBlogBilgisiGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlogBilgisiGuncelleActionPerformed
     if(seciliBlog==null){
         Araclar.mesajGoster("Önce bir blog seciniz!!!", "UYARI");
         return;
     }
     seciliBlog.setAciklama(jTextAreaBlogAciklama.getText());
     seciliBlog.setBlogBaslik(jTextAreaBlogBasligi.getText());
     VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            vt.blogBilgisiGuncelle((Blog) seciliBlog);
            vt.baglantiyiKes();
        } catch (Exception e) {
            Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
    }//GEN-LAST:event_jButtonBlogBilgisiGuncelleActionPerformed

    private void jButtonYeniBlogOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYeniBlogOlusturActionPerformed
     diyalogTemizleBlogOlustur();
     VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            this.kullaniciListesi=vt.tumKullanicilariGetir();
            vt.baglantiyiKes();
        } catch (Exception e) {
               Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
        blogSahibiSeciniz.addItem("Seciniz...");
        if(this.kullaniciListesi!=null){
            for(Kullanici k:this.kullaniciListesi){
            if(k.getK_Izin().equals("A")||k.getK_Izin().equals("Y")){
                blogSahibiSeciniz.addItem(k.getK_adSoyad() + " ( " + k.getK_Email()+ " )");
            }
            
            }
        
        }
        jDialogYeniBlogOlustur.pack();
        jDialogYeniBlogOlustur.setLocationRelativeTo(this);
        jDialogYeniBlogOlustur.setVisible(true);
    }//GEN-LAST:event_jButtonYeniBlogOlusturActionPerformed

    private void jButtonKullaniciBilgisiGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKullaniciBilgisiGoruntuleActionPerformed
         if(seciliBlog==null){
         Araclar.mesajGoster("Önce bir blog seciniz!!!", "UYARI");
         return;
     }
         VeritabaniIslemleri vt=new VeritabaniIslemleri();
         try {
            vt.baglan();
            this.seciliKullanici=vt.kullaniciBilgisiGetir(this.seciliBlog.getK_ID());
            vt.baglantiyiKes();
        } catch (Exception e) {
            Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
         jDialogKullaniciBilgisiDetay.pack();
         jDialogKullaniciBilgisiDetay.setLocationRelativeTo(this);
         jDialogKullaniciBilgisiDetay.setVisible(true);
         
         kIzin.setModel(new DefaultComboBoxModel());
         kIzin.addItem("Yazar (Girdi Ekleyebilir)");
         kIzin.addItem("Okur (Yorum Ekleyebilir)");
         kIzin.addItem("Tüm verilere ulaşabilir");
         
         
         kullaniciAdSoyad.setText(this.seciliKullanici.getK_adSoyad());
         kullaniciAdi.setText(this.seciliKullanici.getK_Email());
         kullaniciSifre.setText(this.seciliKullanici.getK_Sifre());
         switch(this.seciliKullanici.getK_Izin().charAt(0)){
             case 'Y':
                 kIzin.setSelectedIndex(0);
                 break;
             case 'O':
                 kIzin.setSelectedIndex(1);
                 break;
             case 'A':
                 kIzin.setSelectedIndex(2);
                 break;
             default:
                 break;
          
         }
         
         
    }//GEN-LAST:event_jButtonKullaniciBilgisiGoruntuleActionPerformed

    private void jButtonKullaniciİslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKullaniciİslemleriActionPerformed
       jDialogKullaniciBilgileriDuzenle.pack();
       jDialogKullaniciBilgileriDuzenle.setLocationRelativeTo(this);
       jDialogKullaniciBilgileriDuzenle.setVisible(true);
       
       kullaniciTablosuDoldur();
       
        ListSelectionModel lsm=jTable1.getSelectionModel();
        lsm.addListSelectionListener(new ListSelectionListener() {
           @Override
           public void valueChanged(ListSelectionEvent e) {
            int row=jTable1.getSelectedRow();
            if(row==-1){
            return;
            }
            IdGoster.setText(jTable1.getValueAt(row, 0).toString());
            kAdi.setText(jTable1.getValueAt(row, 1).toString());
            kSifre.setText(jTable1.getValueAt(row, 2).toString());
            kAdSoyad.setText(jTable1.getValueAt(row, 3).toString());
           switch(jTable1.getValueAt(row, 4).toString().charAt(0)){
             case 'Y':
                 kIzin.setSelectedIndex(0);
                 break;
             case 'O':
                 kIzin.setSelectedIndex(1);
                 break;
             case 'A':
                 kIzin.setSelectedIndex(2);
                 break;
             default:
                 break;
          
         }
           
           
           }
       });
        
        
        
    }//GEN-LAST:event_jButtonKullaniciİslemleriActionPerformed

    private void jButtonBloguTamamenSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBloguTamamenSilActionPerformed
    if(this.seciliBlog==null){    
         return;
     }
    int cevap=Araclar.soruSor("Blogu silmek istediğnizden " 
            + "eminmisiniz(Blogdaki girdi ve "
            + "yorumlar otomatik olarak silinecek)?");
    if(cevap!=0)
        return;
    
    VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            vt.bloguSil((Blog) seciliBlog);
            vt.baglantiyiKes();
            formuTemizle();
            baslangicBilgisiniCek();
        } catch (Exception e) {
                   Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
    
    
    
    
    
    }//GEN-LAST:event_jButtonBloguTamamenSilActionPerformed

    private void jButtonProgramiKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProgramiKapatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonProgramiKapatActionPerformed

    private void blogOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogOlusturActionPerformed
       if(blogBasligi.getText().trim().length()==0){
       Araclar.mesajGoster("Blog Basligi bos olamaz","HATA");
           return;
       }
       if(aciklama.getText().trim().length()==0){
       Araclar.mesajGoster("Bir aciklama giriniz","UYARI");
           return;
       }
       if(blogSahibiSeciniz.getSelectedItem().toString().equals("Seciniz...")){
       Araclar.mesajGoster("Önce bir blog seciniz..","UYARI");
           return;
       }
       Blog b=new Blog();
       b.setAciklama(aciklama.getText());
       b.setBlogBaslik(blogBasligi.getText());
       b.setK_ID(this.seciliKullanici.getK_ID());
       b.setOlusturmaTarihi(Araclar.yeniTimeStampOlustur());
        VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            vt.blogOlustur(b);
            vt.baglantiyiKes();
        } catch (Exception e) {
                 Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
       formuTemizle();
       baslangicBilgisiniCek();
       
    }//GEN-LAST:event_blogOlusturActionPerformed

    private void kullaniciGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciGuncelleActionPerformed
       this.seciliBlog.getKullanici().setK_adSoyad(kullaniciAdSoyad.getText());
       this.seciliBlog.getKullanici().setK_Email(kullaniciAdi.getText());
       this.seciliBlog.getKullanici().setK_Sifre(kullaniciSifre.getText());
       this.seciliBlog.getKullanici().setK_Izin(kullaniciIzin.getSelectedItem().toString().substring(0,1));
       VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            vt.kullaniciBilgisiGuncelle(seciliBlog.getKullanici());
            vt.baglantiyiKes();
            jLabel12.setText(this.seciliBlog.getKullanici().getK_adSoyad());
        } catch (Exception e) {
            Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
    }//GEN-LAST:event_kullaniciGuncelleActionPerformed

    private void yeniKullaniciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeniKullaniciEkleActionPerformed
     IdGoster.setText("");
     kAdi.setText("");
     kSifre.setText("");
     kAdSoyad.setText("");
     kIzin.setSelectedIndex(0);
    }//GEN-LAST:event_yeniKullaniciEkleActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
       Kullanici k=new Kullanici();
       k.setK_adSoyad(kAdSoyad.getText());
       k.setK_Email(kAdi.getText());
       k.setK_Izin(kIzin.getSelectedItem().toString().substring(0,1));
       k.setK_Sifre(kSifre.getText());
       k.setKayitTarih(Araclar.yeniTimeStampOlustur());
       VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            vt.kullaniciOlustur(k);
            vt.baglantiyiKes();
            kullaniciTablosuDoldur();
        } catch (Exception e) {
            Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
       
    }//GEN-LAST:event_ekleActionPerformed

    private void KGüncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KGüncelleActionPerformed
       if(IdGoster.getText().trim().length()==0){
           return;
       }
        
        Kullanici k=new Kullanici();
        k.setK_ID(Integer.valueOf(IdGoster.getText()));
       k.setK_adSoyad(kAdSoyad.getText());
       k.setK_Email(kAdi.getText());
       k.setK_Izin(kIzin.getSelectedItem().toString().substring(0,1));
       k.setK_Sifre(kSifre.getText());
       VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            boolean sonuc=vt.kullaniciBilgisiGuncelle(k);
            vt.baglantiyiKes();
            if(sonuc){
            kullaniciTablosuDoldur();
            }
        } catch (Exception e) {
            Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
    }//GEN-LAST:event_KGüncelleActionPerformed

    private void kSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kSilActionPerformed
         if(IdGoster.getText().trim().length()==0){
             Araclar.mesajGoster("Önce bir blog seciniz..","UYARI");
             return;
       }
         int cevap=Araclar.soruSor("Kullanıcıyı silmek istediğinizden "
         +"eminmisiniz?(Kullanıcının tüm blog , girdi ve"
         +" yorumları otoatik olarak silinecek)");        
          if(cevap!=0)
              return;
          
          VeritabaniIslemleri vt=new VeritabaniIslemleri();
          try {
            vt.baglan();
            Kullanici k=new Kullanici();
            k.setK_ID(Integer.valueOf(IdGoster.getText()));
            vt.kullaniciyiSil(k);
            vt.baglantiyiKes();
            kullaniciTablosuDoldur();
            formuTemizle();
            baslangicBilgisiniCek();
        } catch (Exception e) {
            Araclar.mesajGoster("Bir hata olustu.Acıklama "+e.getMessage(),"HATA");
        }
    }//GEN-LAST:event_kSilActionPerformed

    public void formuTemizle(){
    jLabelOlusturulmaTarihi.setText("");
    jLabelBlogSahibi.setText("");
    jLabelToplamGirdiSayisi.setText("-");
    jLabelToplamYorumSayisi.setText("-");
    jTextAreaBlogAciklama.setText("");
    jTextAreaBlogBasligi.setText("");
 }
    public void diyalogTemizleBlogOlustur(){
        //Blog Olustur Diyaloğu
        blogBasligi.setText("");
        aciklama.setText("");
        blogSahibiSeciniz.setModel(new DefaultComboBoxModel());
       
    }
    public void baslangicBilgisiniCek(){
        try {
            VeritabaniIslemleri vt=new VeritabaniIslemleri();
            vt.baglan();
            this.blogListesi=vt.tumBloglariGetir();
            jComboBoxBlogListesi.setModel(new DefaultComboBoxModel());
            jComboBoxBlogListesi.addItem("Seciniz...");
            if(this.blogListesi==null){
                return;}
            for (Blog b : this.blogListesi) {
                jComboBoxBlogListesi.addItem(Araclar.tarihZamnGoster(b.getOlusturmaTarihi())
                +"...."
                +b.getBlogBaslik());
                
            }
            vt.baglantiyiKes();
        } catch (Exception e) {
        Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
    }
    public void kullaniciTablosuDoldur(){
        VeritabaniIslemleri vt=new VeritabaniIslemleri();
        try {
            vt.baglan();
            Object[][] veri=kullaniciBilgisiniIkiBoyutluDiziyeCevir(vt.tumKullanicilariGetir());
            Object [] baslik=vt.tabloKolonAdlariniGetir("kullanicilar");
            jTable1.setModel(Araclar.tabloIcinModelOlustur(baslik, veri));
            TableModel model=new DefaultTableModel(veri,baslik);
            jTable1.setModel(model);
            vt.baglantiyiKes();
        } catch (Exception e) {
            Araclar.mesajGoster("Bir Hata Olustu.Açıklama: " + e.getMessage(),"HATA");
        }
    
    }
       public Object[][] kullaniciBilgisiniIkiBoyutluDiziyeCevir(List<Kullanici> kList) {
        if (kList == null) {
            return null;
        }
        Object[][] sonuc = new Object[kList.size()][6];

        for (int i = 0; i < kList.size(); i++) {
            sonuc[i][0] = kList.get(i).getK_ID();
            sonuc[i][1] = kList.get(i).getK_Email();
            sonuc[i][2] = kList.get(i).getK_Sifre();
            sonuc[i][3] = kList.get(i).getK_adSoyad();
            sonuc[i][4] = kList.get(i).getK_Izin();
            sonuc[i][5] = kList.get(i).getKayitTarih();
        }


        return sonuc;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlogYoneticisiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlogYoneticisiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlogYoneticisiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlogYoneticisiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlogYoneticisiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdGoster;
    private javax.swing.JButton KGüncelle;
    private javax.swing.JTextArea aciklama;
    private javax.swing.JTextArea blogBasligi;
    private javax.swing.JButton blogOlustur;
    private javax.swing.JComboBox<String> blogSahibiSeciniz;
    private javax.swing.JButton ekle;
    private javax.swing.JButton jButtonBlogBilgisiGuncelle;
    private javax.swing.JButton jButtonBloguTamamenSil;
    private javax.swing.JButton jButtonKullaniciBilgisiGoruntule;
    private javax.swing.JButton jButtonKullaniciİslemleri;
    private javax.swing.JButton jButtonProgramiKapat;
    private javax.swing.JButton jButtonYeniBlogOlustur;
    private javax.swing.JComboBox<String> jComboBoxBlogListesi;
    private javax.swing.JDialog jDialogKullaniciBilgileriDuzenle;
    private javax.swing.JDialog jDialogKullaniciBilgisiDetay;
    private javax.swing.JDialog jDialogYeniBlogOlustur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBlogSahibi;
    private javax.swing.JLabel jLabelOlusturulmaTarihi;
    private javax.swing.JLabel jLabelToplamGirdiSayisi;
    private javax.swing.JLabel jLabelToplamYorumSayisi;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaBlogAciklama;
    private javax.swing.JTextArea jTextAreaBlogBasligi;
    private javax.swing.JTextField kAdSoyad;
    private javax.swing.JTextField kAdi;
    private javax.swing.JComboBox<String> kIzin;
    private javax.swing.JPasswordField kSifre;
    private javax.swing.JButton kSil;
    private javax.swing.JTextField kullaniciAdSoyad;
    private javax.swing.JTextField kullaniciAdi;
    private javax.swing.JButton kullaniciGuncelle;
    private javax.swing.JComboBox<String> kullaniciIzin;
    private javax.swing.JPasswordField kullaniciSifre;
    private javax.swing.JButton yeniKullaniciEkle;
    // End of variables declaration//GEN-END:variables
}
